### ISSUE TITLE
crew_multiple_tasks error

### ISSUE THREAD

**Issue by whitejf** [hypebright/async_shiny#16]
I'm starting with crew to modify a shiny app with many modules to improve startup time and performance a few places.  That lead me to you as I am looking for sample code that I can use to build a crew server module to call as needed.  The multiple tasks code in git is erroring when running:  Error: (converted from warning) Error in status_message: attempt to apply non-function

I want to make sure the edit I made is correct and find out if there is a better way to do it:
line 145 was:  reactive_status(status_message(n = sum(controller$schedule$summary())))
I revised line 145 to be:     reactive_status(status_message(n = sum(controller$pushed) - sum(controller$popped))).

**Comment by hypebright** [comment]
@whitejf crew has seen a lot of [changes](https://wlandau.github.io/crew/news/index.html) over the last few months, so I'm going to update the examples to match the latest version. 

Looking at this [documentation](https://wlandau.github.io/crew/articles/introduction.html#summaries) very briefly, I think we can also use `controller$summary()$tasks` or `controller$launcher$summary()$complete` to get the number of completed tasks, where the latter will also return terminated instances.

**Comment by whitejf** [comment]
thanks for the response.  You asked for suggestions for the future.  Attached is the work i did to modularize your code; although, it could (and maybe should) just be a function.  I think this idea is a little beyond my ability right now, but it would be helpful if you could create the following and share it for us all.

Background - my shiny app has a lot of database calls, some large, some long calculations with large amounts of data, and some complex visualizations.  Thats where i want to add the benefits of crew. Ideally I'd like to offload these processes to other sessions and return results to the main session where they are stored fand used.

Can Shiny's ExtendedTask class be used with the crew function/module to initiate the processing of the long tasks and then return the completed results, with just a single call to the function? it would make sense to me if the $new, invoke, status, results, and clone methods could all be organized in one module/function with a low-overhead worker manager like crew.

Maybe there's a better way, but it would be a great blog or video post.

Thanks,

John
[crew_async_revised_to_include_module.txt](https://github.com/user-attachments/files/16033110/crew_async_revised_to_include_module.txt)

**Comment by hypebright** [comment]
@whitejf I just updated the `crew` examples.

Thanks for your suggestion about creating a function/module and combining it with `ExtendedTask`. I'll look into it!

**Comment by whitejf** [comment]
Thanks. I’ll be interested in seeing what you come up with. My last 
attempt was setting up a dummy function with … and passing the  the real 
function and arguments at the time i called the function/module
